# Generated by Django 5.1 on 2024-08-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('titlemaking', models.CharField(max_length=255)),
                ('descriptionmaking', models.TextField()),
                ('image', models.ImageField(upload_to='making/')),
                ('titleparadise', models.CharField(max_length=255)),
                ('titlexperiences', models.CharField(max_length=255)),
                ('titletrips', models.CharField(max_length=255)),
                ('descriptiontrips', models.TextField()),
                ('titletravels', models.CharField(max_length=255)),
                ('descriptiontravels', models.TextField()),
                ('titleblog', models.CharField(max_length=255)),
                ('titlestaff', models.CharField(max_length=255)),
                ('titlepartners', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройка главной страницы',
            },
        ),
    ]
