# Generated by Django 5.1 on 2024-08-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='image_making',
            field=models.ImageField(default=1, upload_to='making/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='main',
            name='image',
            field=models.ImageField(upload_to='main/'),
        ),
    ]
