# Generated by Django 5.1 on 2024-08-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_forms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forms',
            options={'verbose_name_plural': 'Форма'},
        ),
        migrations.AddField(
            model_name='forms',
            name='image',
            field=models.ImageField(default=1, upload_to='forms', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
