# Generated by Django 5.1 on 2024-08-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_forms_options_forms_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='forms', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Трипы',
            },
        ),
    ]
