# Generated by Django 5.1 on 2024-08-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='forms2', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Формы2',
            },
        ),
    ]
