# Generated by Django 5.1 on 2024-08-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_minilogo_description_minilogo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minilogo',
            name='description',
        ),
    ]
