# Generated by Django 5.1 on 2024-08-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_minilogo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='stuffs', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'stuffs',
            },
        ),
    ]
