# Generated by Django 5.1 on 2024-08-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_stuffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'logos',
            },
        ),
    ]
