# Generated by Django 5.1 on 2024-08-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='forms4', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Формы4',
            },
        ),
    ]
